/// <reference types="node" />

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // We use bracket notation to ensure TypeScript doesn't 
    // complain if the environment variable is missing during build time
    url: process.env["DATABASE_URL"] ?? "",
  },
});